---

  - name: 10.1.1 Set Password Expiration Days (Scored)
    lineinfile: >
        dest='/etc/login.defs'
        line='PASS_MAX_DAYS 90'
        state=present
        regexp='^PASS_MAX_DAYS'
    tags:
      - section10
      - section10.1
      - section10.1.1

  - name: 10.1.2 Set Password Change Minimum Number of Days (Scored)
    lineinfile: >
        dest='/etc/login.defs'
        line='PASS_MIN_DAYS 7'
        regexp='^PASS_MIN_DAYS'
    tags:
      - section10
      - section10.1
      - section10.1.2

  - name: 10.1.3 Set Password Expiring Warning Days (Scored)
    lineinfile: >
        dest='/etc/login.defs'
        line='PASS_WARN_AGE'
        regexp='^PASS_WARN_AGE'
    tags:
      - section10
      - section10.1
      - section10.1.3

  - name: 10.2 Disable System Accounts (check) (Scored)
    shell: awk -F':' '($1!="root" && $1!="sync" && $1!="shutdown" &&$1!="halt" && $3<500 && $7!="/usr/sbin/nologin" && $7!="/bin/false") {print $1}' /etc/passwd
    register: awk_etc_passwd
    changed_when: False
    tags:
      - section10
      - section10.2

  - name: 10.2 Disable System Accounts (Scored)
    command: /usr/sbin/usermod -s /usr/sbin/nologin {{ item }}
    with_items: "{{awk_etc_passwd.stdout_lines | default([])}}"
    tags:
      - section10
      - section10.2

  - name: 10.3 Set Default Group for root Account (Scored)
    user: >
        name=root
        group=root
    tags:
      - section10
      - section10.3

  - name: 10.4 Set Default umask for Users (Scored)
    lineinfile: >
        dest=/etc/login.defs
        line='UMASK\t077'
        regexp='^UMASK'
        state=present
    tags:
      - section10
      - section10.4

  - name: 10.5 Lock Inactive User Accounts (check) (Scored)
    command: grep INACTIVE /etc/login.defs
    changed_when: False
    failed_when: False
    always_run: True
    register: lock_inactive_rc
    tags:
      - section10
      - section10.5
        
  - name: 10.5 Lock Inactive User Accounts (Scored)
    lineinfile: >
        dest=/etc/login.defs
        line='INACTIVE=35'
        state=present
    when: lock_inactive_rc.rc == 1
    tags:
      - section10
      - section10.5

